name: cjhms
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.4.5
  # Dart 常用工具类库
  common_utils: ^1.0.9
  #  网络库
  dio: ^1.0.13
  cookie_jar: ^0.0.7
  #  滑动删除
  flutter_slidable: "^0.4.9"
  flutter_circular_chart: ^0.1.0
  # 轻量数据存储
  shared_preferences: 0.5.1+1
  # 网络图片加载
  cached_network_image: ^0.6.0
  # 下拉刷新
  pull_to_refresh: ^1.1.6
  # rx
  rxdart: ^0.18.1
  # 提示dialog
  tip_dialog: ^2.0.0
  # 吐司
  fluttertoast: ^2.1.1
  # json序列化
  json_annotation: ^2.0.0
  # 判断网络
  connectivity: ^0.3.2
  image_cropper: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json序列化，命令行自动生成model类的工具
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/launch_screen.png
    - assets/images/my_bg.png
    - assets/images/login_bg.png
    - assets/images/archieve_bg.png

  fonts:
    - family: appIconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf

